kibana:
  image: billkoch/kibana:3.0.1
  ports:
    - "80:8080"
  links:
    - elasticsearch
elasticsearch:
  image: elasticsearch:1.3.9
  volumes:
    - ./elasticsearch/data:/data
  ports:
    - "9200:9200"
    - "9300:9300"
rabbitmq:
  image: library/rabbitmq:3.5.1-management
  ports:
    - "5672:5672"
    - "15672:15672"

logstash:
  image: billkoch/logstash:1.4.2
  links:
    - elasticsearch
    - rabbitmq
  volumes:
    - ./logstash:/opt/logstash/conf
